### ISSUE TITLE
Add option to work with any camera

### ISSUE THREAD

**Issue by TisFoolish** [art0007i/CapturePrivateUI#1]
I can't use finger photos because of a disability (I am physically unable to summon the camera), so I have my own, custom solution. Sadly this also means I can't use the mod.

**Comment by art0007i** [comment]
added an option that allows you to select a tag for cameras that should render private ui in [1.1.0](https://github.com/art0007i/CapturePrivateUI/releases/tag/1.1.0). hopefully this is good enough
